title: kevin's digital garden
description: After reading about the concept of digital gardens, I was excited to try it out for myself
author:
  name: Kevin Wyckmans
  email: kevinwyckmans@gmail.com

page_excerpts: true
show_excerpts: true

exclude:
  - Gemfile
  - Gemfile.lock

author:
  name: Kevin Wyckmans
  email: kevinwyckmans@gmail.com
  github: kwyckmans
  twitter: kwyckmans

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true